name: Go CI

on:
  push:
    branches: [ "**" ]
  pull_request:
  workflow_dispatch:

jobs:
  build-and-test:
    runs-on: ubuntu-latest
    name: Build and Test
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          submodules: recursive

      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: '1.22'

      - name: Build
        run: go build ./...

      - name: Test
        run: go test -short ./...

  build-and-test-coverage:
    runs-on: ubuntu-latest
    name: Test Coverage
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          submodules: recursive

      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: '1.22'

      - name: Run Tests with Coverage
        run: |
          go test -coverprofile=coverage.out ./...
          grep -v "main.go" coverage.out > coverage_filtered.out
          go tool cover -func coverage_filtered.out

      - name: Convert Coverage to Cobertura
        run: |
          go install github.com/boumenot/gocover-cobertura@latest
          gocover-cobertura < coverage.out > coverage.xml

      - name: Upload coverage reports to Codecov
        uses: codecov/codecov-action@v5
        with:
          token: ${{ secrets.CODECOV_TOKEN }}

  static-check:
    runs-on: ubuntu-latest
    name: Static Analysis
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          submodules: recursive

      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: '1.22'

      - name: Run Staticcheck
        run: |
          go install honnef.co/go/tools/cmd/staticcheck@latest
          staticcheck ./... > check.txt
          if [ -s check.txt ]; then
            echo "Static analysis failed"; cat check.txt; exit 1
          else
            echo "No issues found"
          fi

      - name: Upload Report on Failure
        if: failure()
        uses: actions/upload-artifact@v4
        with:
          name: staticcheck-report
          path: check.txt
